name: Cross-Compile Zig Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_release:
    name: Build and Zip Artifacts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-windows-gnu # Windows
            os_name: win-x64
          - target: x86_64-linux-gnu # Linux
            os_name: linux-x64
          - target: aarch64-linux-gnu # Linux ARM
            os_name: linux-arm64
          - target: aarch64-macos-none # MacOS Apple Silicon
            os_name: macos-arm64
          - target: x86_64-macos-none # MacOS Intel
            os_name: macos-x64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.15.2 # Pinning to stable to avoid nightly mirror 404/503 errors

      - name: Build Library for ${{ matrix.target }}
        run: zig build -Dtarget=${{ matrix.target }} -Doptimize=ReleaseFast

      - name: Package Release Zip
        run: |
          cd zig-out
          zip -r ../simdb-${{ matrix.os_name }}.zip include lib
          cd ..

      - name: Upload Artifact to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: simdb-${{ matrix.os_name }}.zip
